### ISSUE TITLE
Demo

### ISSUE THREAD

**Issue by mhajder** [fncnt/vncnt-hugo#10]
Can you add a link to the demo version?
You can host it, for example, on Netlify.

**Comment by fncnt** [comment]
I don't really see a use case for netlify here. Have a look at the [theme directory](https://themes.gohugo.io/vncnt-hugo/) for a demo. Unfortunately, it seems the directory updates themes periodically, so some features might not work yet on the demo page (should only concern the dark mode, afaik). 

Alternatively, use `hugo new site demosite` to create a new website, then [install](https://github.com/fncnt/vncnt-hugo/blob/master/README.md#installation) and [configure](https://github.com/fncnt/vncnt-hugo/blob/master/README.md#configuration) the theme. Finally, run your own local demo using `hugo server -w`.
