### ISSUE TITLE
Removing the preset keys

### ISSUE THREAD

**Issue by graynk** [fncnt/vncnt-hugo#14]
Hi! Love your theme. I've got a question though: the suggested way of installing the theme is using git submodules. How would one go about removing the preset keys in theme's config.toml? I don't have twitter/instagram/ello and want to remove them for my site. But hugo insists on merging the two configs, even if I specify just my config. So I end with my links intermixed with links specified in theme's config.toml as an example. Is there a way to remove them without changing the theme files?

**Comment by bryanasdev000** [comment]
Hi there, how is your root `config.toml`? 

I am using this theme at https://hello.bryanalbuquerque.dev/ and Hugo does not merge the "defaults" keys from the theme config.

I am using it as as git submodule at `themes/vncnt-hugo` and here it is my `config.toml` at my hugo root directory:

```
baseURL = "https://hello.bryanalbuquerque.dev/"
buildDrafts = false
buildFuture = false
buildExpired = false
relativeURLs = true
disableRSS = true
enableRobotsTXT = true
languageCode = "pt"
language = "pt"
theme = "vncnt-hugo"
title = "Hello World · Bryan Albuquerque"
_merge = "none"
[permalinks]
  fixed = ":title/"
  posts = "posts/:slug/"
[params]
  author = "Bryan Albuquerque"
  description = "Landing Page"
  bio = "Open Source Technomancer.  \n  DevOps Engineer."
  avatar = "img/avatar.png"
  favicon = "img/favicon.ico"
  error404 = "ERR_404"
  [params.contact]
    github = "https://github.com/bryanasdev000"
    gitlab = "https://gitlab.com/bryanasdev000"
    linkedin = "https://www.linkedin.com/in/bryanasdev000/"
    [params.contact.1]
      name = "blog"
      icon = "globe"
      style = "fas"
      link = "https://blog.bryanalbuquerque.dev"
    [params.contact.2]
      name = "wiki"
      icon = "book"
      style = "fas"
      link = "https://wiki.bryanalbuquerque.dev"
```

**Comment by graynk** [comment]
> Hi there, how is your root `config.toml`?
> 

Here's mine: https://github.com/graynk/space/blob/master/config.toml

**Comment by fncnt** [comment]
Hey :) First of all, I appreciate you guys using my theme!

The important line in @bryanasdev000's config is `_merge = "none"`.
 
 @graynk, if you include this line in your config, it should work. A couple of versions ago, Hugo started merging configs by default.
 Your config looks like it was copied from an older version of my example `config.toml`. The current example includes this line. 
 Also, adding the `hardLineBreak` extension shouldn't be necessary anymore. If I'm not mistaken a double-space followed by `\n` should suffice for hard line breaks.
 
 Let me know if this helped.

**Comment by graynk** [comment]
> Hey :) First of all, I appreciate you guys using my theme!
> 
> The important line in @bryanasdev000's config is `_merge = "none"`.
> 

Thanks! That's exactly the setting that I was looking for, it works now, thank you
