### ISSUE TITLE
Adding icons

### ISSUE THREAD

**Issue by M-Brody** [fncnt/vncnt-hugo#3]
Thanks for your work on this landing page template!

I'm trying to add an icon next to the twitter icon for strava. I have configured my config.toml and included the url to my strava page. I also noticed that the strava icon is included in the all.mine.css file. But it does not show up when I push and redeploy.

How do I pull the icon from that css file and display it as a clickable option?

I also could just be dense (I'm very new to website dev) but the url's I input into my config.toml for twitter and GitHub do not seem to be working. Any help would be appreciated! Thank you!

https://github.com/M-Brody/mattbrody-website

**Comment by fncnt** [comment]
I made [some patches](https://github.com/fncnt/vncnt-hugo/files/2861353/strava-link-patches.zip) that hopefully should be self-explanatory.
You can apply them to your [`HEAD`](https://github.com/M-Brody/mattbrody-website/commit/5d300be239169492ca5f303d7616b05af58e5386) (as of now) by typing:
```
git am *.patch
```
This will automatically commit those patches. 
If you want to be safe, use
```
git apply some-patch.patch
```
and commit the changes yourself.

Also, these [two](https://gohugo.io/templates/lookup-order/#hugo-layouts-lookup-rules-with-theme) [links](https://fontawesome.com/icons/strava?style=brands) might be interesting to you.

I'll update the `README.md` file in my repo to include detailed instructions about modifying the contact section when I got more time to spare ;)
